const emptyProduct = {
  idProducto: 0,
  principal: 0,
  codigo: "",
  descripcion: "",
  costo: 0,
  margenGanancia: 0.0,
  precio: 0,
  precioConImpuesto: 0,
  idUnidadMedida: 0,
  idMetodoCosteo: 0,
  idImpuesto: 0,
  idCategoria: 0,
  idLineaNegocio: 0,
  productoInventariable: false,
  reorden: 0,
  inventarioMinimo: 0,
  inventarioMaximo: 0,
  claveProductoServicio: "",
  claveUnidadMedida: "",
  idTipoProductoServicio: 28,
  idEstatus: 0,
  idSesion: 0,
};

export { emptyProduct };
